# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Application-Dispatch-BuildURI
version:      0.01
version_from: lib/CGI/Application/Dispatch/BuildURI.pm
installdirs:  site
requires:
    CGI::Application::Plugin::Redirect: 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
